apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jw-django/observability-gitops.git
    targetRevision: main
    path: gitops/charts/spring-boot-app
    helm:
      values: |
        nameOverride: order-service
        image:
          repository: devjw/order-service
          tag: 20260427-150434-39d9bfc
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
          JAVA_OPTS: "-XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError"
  destination:
    server: https://kubernetes.default.svc
    namespace: msa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true