apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jw-django/observability-gitops.git
    targetRevision: main
    path: gitops/charts/spring-boot-app
    helm:
      values: |
        image:
          repository: devjw/order-service
          tag: 20260421-110500-41d755e
        nameOverride: order-service
  destination:
    server: https://kubernetes.default.svc
    namespace: msa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true