apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jw-django/observability-gitops.git
    targetRevision: main
    path: gitops/charts/spring-boot-app
    helm:
      values: |
        nameOverride: payment-service
        image:
          repository: devjw/payment-service
          tag: 20260427-143052-7f68832
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
          JAVA_OPTS: "-XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError"
  destination:
    server: https://kubernetes.default.svc
    namespace: msa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true