deploymentStrategy:
  type: Recreate

adminPassword: "admin"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://loki-gateway.monitoring.svc.cluster.local:80
        access: proxy
      - name: Tempo
        type: tempo
        url: http://tempo-cluster.monitoring.svc.cluster.local:3200
        access: proxy

persistence:
  enabled: true
  type: pvc
  storageClassName: standard 
  accessModes:
    - ReadWriteOnce
  size: 5Gi

ingress:
  enabled: false
